version: '3.8'

services:  
  minio-mlflow:
    image: quay.io/minio/minio:RELEASE.2022-06-25T15-50-16Z
    command: ["minio", "server", "--address", "0.0.0.0:9000", "--console-address", "0.0.0.0:9001", "/data"]
    expose:
      - 9000  # server
      - 9001  # console
    networks:
      - mlflow
    env_file:
      - .env
      - .env.secret
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 20s
      retries: 3
    volumes:
      - minio_mlflow:/data
    profiles: 
      - storage
      - server
  
  nginx-minio-mlflow:
    image: nginx:1.19.2-alpine
    volumes:
      - ./minio/nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - 9000  # server
      # - 9001  # console
    ports:
      # - 9000:9000  # server
      - 9001:9001  # console
    networks:
      - mlflow
    depends_on:
      - minio-mlflow
    restart: always
    profiles: 
      - storage
      - server
  
  minio-mlflow-init:
    image: quay.io/minio/mc:RELEASE.2023-08-15T23-03-09Z
    env_file:
      - .env
      - .env.secret
    networks:
      - mlflow
    depends_on:
      - minio-mlflow
    volumes:
      - ./minio/init.sh:/init.sh
    entrypoint: bash -c "./init.sh"
    profiles: 
      - storage
      - server
    
  postgres-mlflow:
    image: postgres:15.4
    env_file:
      - .env
      - .env.secret
    volumes:
       - postgres_mlflow:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - mlflow
    restart: always
    profiles: 
      - server
      
  pgadmin-mlflow:
    image: dpage/pgadmin4:7.5
    restart: always
    env_file:
      - .env
      - .env.secret
    environment:
      PGADMIN_LISTEN_PORT: 5050
    volumes:
       - pgadmin_mlflow:/var/lib/pgadmin
    ports:
      - 5050:5050
    networks:
      - mlflow
    profiles: 
      - server
      
  mlflow:
    image: mlflow  # TODO Use MLflow official image if it adds boto3 and psycopg2 packages
    build: ./mlflow    
    expose:
      - 5000
    networks:
      - mlflow
    env_file:
      - .env
      - .env.secret
    environment:
      MLFLOW_S3_ENDPOINT_URL: "http://nginx-minio-mlflow:9000"
    depends_on:
      - minio-mlflow-init
      - postgres-mlflow
    # backend-store-uri template "postgresql://user:password@host:port/db"
    entrypoint: >
      /bin/sh -c "
      AWS_ACCESS_KEY_ID=$${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY=$${MINIO_ROOT_PASSWORD}
      mlflow server 
      --backend-store-uri postgresql://$${POSTGRES_USER}:$${POSTGRES_PASSWORD}@postgres-mlflow:5432/$${POSTGRES_DB}
      --artifacts-destination s3://$${MINIO_MLFLOW_BUCKET_NAME} 
      --serve-artifacts 
      --host 0.0.0.0"
    restart: always
    profiles: 
      - server

  nginx-mlflow:
    image: nginx:1.19.2-alpine
    volumes:
      - ./mlflow/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.htpasswd:/etc/nginx/.htpasswd
    ports:
       - 5000:5000
    networks:
      - mlflow
    depends_on:
      - mlflow
    restart: always
    profiles: 
      - server
    
networks:
  mlflow:
    driver: bridge

volumes:
  minio_mlflow:
  postgres_mlflow:
  pgadmin_mlflow: